{
 "title": "PowerTiger",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Live Power Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({room!=\"\"}) * 240.0 / 1000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Amps Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({room!=\"\"}) / 1000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live Room Power Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(6, sum by (room) ({room!=\"\"})) * 240.0 / 1000.0    ",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Power Consumption by Terminals",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{room!=\"\"} * 240.0 / 1000.0",
     "legendFormat": "{{room}} - {{device}}"
    }
   ]
  },
  {
   "title": "Power Consumption by Rooms",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (room) ({room!=\"\"}) * 240.0 / 1000.0",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Hourly Power Consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(avg_over_time({room!=\"\"}[1m])) * 240.0 / 1000.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Power Consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(avg_over_time({room!=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}